import { EmailColumnStyles, EmailElement, EmailSection, EmailTemplateDefinition, EmailTemplateScenario, EmailTemplateType } from '../../models/email-template-designer.model';

export type StarterEmailTemplate = Omit<EmailTemplateDefinition, 'companyId'> & { description: string; accent: string; audience: string; scenario: EmailTemplateScenario };

const defaultColumnStyles = (): EmailColumnStyles => ({ backgroundColor: '#ffffff', verticalAlign: 'top', paddingTop: 0, paddingRight: 0, paddingBottom: 0, paddingLeft: 0, borderColor: '#e2e8f0', borderWidth: 0, borderRadius: 0 });
const section = (elements: EmailElement[], backgroundColor = '#ffffff', paddingTop = 24, paddingBottom = 24): EmailSection => ({ id: crypto.randomUUID(), type: 'layout', columnWidths: [100], styles: { backgroundColor, contentWidth: 600, columnGap: 0, paddingTop, paddingRight: 28, paddingBottom, paddingLeft: 28 }, columns: [{ id: crypto.randomUUID(), styles: defaultColumnStyles(), elements }] });
const text = (content: string, fontSize = 16, fontWeight = '400', color = '#071f4d', textAlign: 'left'|'center'|'right' = 'left', backgroundColor = '#ffffff'): EmailElement => ({ id: crypto.randomUUID(), type: 'text', content, styles: { fontSize, fontWeight, fontStyle: 'normal', textAlign, color, backgroundColor, lineHeight: 1.5, paddingTop: 8, paddingRight: 8, paddingBottom: 8, paddingLeft: 8 } });
const spacer = (height: number): EmailElement => ({ id: crypto.randomUUID(), type: 'spacer', height });
const tpl = (id: string, type: EmailTemplateType, scenario: EmailTemplateScenario, name: string, description: string, subject: string, accent: string, audience: string, heading: string, body: string, cta: string): StarterEmailTemplate => ({ schemaVersion: 1, id, type, scenario, name, description, subject, accent, audience, sections: [section([text(heading, 26, '700', '#ffffff', 'left', accent), text(body), spacer(12), text(cta, 16, '700', accent)], accent, 26, 18), section([text('Thanks,\n{{company.name}}', 15, '600')], '#f8fbff', 18, 22)] });

export function createStarterEmailTemplates(): StarterEmailTemplate[] {
  return [
    tpl('invoice-polished', 'invoice', 'invoice-sending', 'Polished invoice', 'A confident invoice delivery email with clear payment details.', 'Invoice {{invoice.number}} is ready from {{company.name}}', '#2563eb', 'Professional clients', 'Invoice {{invoice.number}} is ready', 'Hi {{client.name}},\n\nYour invoice from {{company.name}} is attached for review. The current total is {{invoice.total}} and payment is due by {{invoice.dueDate}}.\n\nPlease include reference {{invoice.number}} with your payment.', 'Review the attached invoice and let us know if anything needs attention.'),
    tpl('invoice-friendly', 'invoice', 'invoice-sending', 'Friendly handoff', 'A warmer invoice email for ongoing relationships.', 'Your {{company.name}} invoice: {{invoice.number}}', '#0f766e', 'Repeat customers', 'A quick invoice note', 'Hi {{client.name}},\n\nThanks again for working with us. We have attached invoice {{invoice.number}} for {{invoice.total}}. It is due on {{invoice.dueDate}}.\n\nWe appreciate your prompt payment.', 'Have questions? Reply to this email and we will help.'),
    tpl('invoice-concise', 'invoice', 'invoice-sending', 'Concise invoice', 'A short, direct invoice delivery note for busy recipients.', 'Invoice {{invoice.number}} · {{invoice.total}} due {{invoice.dueDate}}', '#0369a1', 'Busy finance teams', 'Your invoice is attached', 'Hello {{client.name}},\n\nPlease find invoice {{invoice.number}} from {{company.name}} attached. The total is {{invoice.total}}, due on {{invoice.dueDate}}.\n\nPlease quote {{invoice.number}} when making payment.', 'Reply to this email if you need a purchase order or billing detail updated.'),
    tpl('invoice-premium', 'invoice', 'invoice-sending', 'Premium invoice delivery', 'A polished, high-touch note for valued client relationships.', 'A note and invoice from {{company.name}}', '#7c3aed', 'High-touch clients', 'Thank you for your business', 'Dear {{client.name}},\n\nIt has been a pleasure working with you. Attached is invoice {{invoice.number}} for {{invoice.total}}, payable by {{invoice.dueDate}}.\n\nWe value your partnership and appreciate your attention to the invoice.', 'If we can make the payment process easier, simply reply and let us know.'),
    tpl('reminder-before-due', 'payment-reminder', 'before-due-reminder', 'Before-due reminder', 'A low-pressure reminder before the due date.', 'Upcoming payment reminder: invoice {{invoice.number}}', '#7c3aed', 'Approachable follow-ups', 'Friendly payment reminder', 'Hi {{client.name}},\n\nThis is a quick reminder that invoice {{invoice.number}} for {{invoice.total}} is due on {{invoice.dueDate}}.\n\nIf payment is already arranged, thank you and please disregard this note.', 'We are happy to help if you need anything from us.'),
    tpl('reminder-due-today', 'payment-reminder', 'due-today-reminder', 'Due today reminder', 'A clear note for payments due today.', 'Invoice {{invoice.number}} is due today', '#ea580c', 'Busy accounts teams', 'Payment due today', 'Hello {{client.name}},\n\nInvoice {{invoice.number}} for {{invoice.total}} is due today.\n\nPlease use {{invoice.number}} as the payment reference.', 'Please confirm once payment has been scheduled.'),
    tpl('reminder-overdue', 'payment-reminder', 'overdue-reminder', 'Overdue follow-up', 'A professional follow-up for invoices past due.', 'Overdue invoice {{invoice.number}} from {{company.name}}', '#dc2626', 'Overdue accounts', 'Invoice now overdue', 'Hi {{client.name}},\n\nOur records show invoice {{invoice.number}} for {{invoice.total}} was due on {{invoice.dueDate}} and still needs attention.\n\nPlease arrange payment or let us know if there is an issue.', 'Reply with an expected payment date so we can update our records.'),
    tpl('overdue-notice', 'payment-reminder', 'overdue-notice', 'Formal overdue notice', 'A firmer notice for escalated overdue accounts.', 'Notice: invoice {{invoice.number}} remains overdue', '#991b1b', 'Escalated collections', 'Overdue payment notice', 'Hello {{client.name}},\n\nInvoice {{invoice.number}} for {{invoice.total}} remains overdue after the due date of {{invoice.dueDate}}.\n\nPlease arrange payment immediately or contact us to resolve this balance.', 'We appreciate your urgent attention to this matter.'),
    tpl('overdue-gentle', 'payment-reminder', 'overdue-reminder', 'Gentle overdue check-in', 'A considerate first follow-up that leaves room for crossed payments.', 'Quick check-in on invoice {{invoice.number}}', '#b45309', 'First overdue follow-ups', 'Did this invoice reach you?', 'Hi {{client.name}},\n\nWe noticed invoice {{invoice.number}} for {{invoice.total}}, due on {{invoice.dueDate}}, appears to be outstanding. It may simply have crossed with your payment.\n\nCould you confirm that the invoice reached the right person?', 'If payment is already on its way, thank you — no further action is needed.'),
    tpl('overdue-payment-plan', 'payment-reminder', 'overdue-notice', 'Payment plan outreach', 'A solution-focused overdue note that invites a practical conversation.', 'Let us resolve invoice {{invoice.number}} together', '#be123c', 'Accounts needing support', 'Let’s agree on the next step', 'Hello {{client.name}},\n\nInvoice {{invoice.number}} for {{invoice.total}} remains unpaid after its due date of {{invoice.dueDate}}. We would like to resolve the balance in a way that works for everyone.\n\nPlease reply with your expected payment date or contact us to discuss an arrangement.', 'A quick response will help us keep your account up to date.'),
    tpl('letter-sending', 'letter', 'letter-sending', 'Letter delivery', 'A concise note for sending formal letters.', 'Letter from {{company.name}}', '#475569', 'Letter recipients', 'A letter is attached', 'Hi {{client.name}},\n\nPlease find the letter from {{company.name}} attached for your records.\n\nContact us if you have any questions after reviewing it.', 'Thank you for your attention.'),
    tpl('general-update', 'general', 'general-email', 'Project update', 'A clean update template for status notes.', 'Update from {{company.name}}', '#4f46e5', 'Project stakeholders', 'Here is the latest update', 'Hello {{client.name}},\n\nWe wanted to share a quick update from {{company.name}}. The key details are listed here so everything is easy to track.\n\nNext step: add your action item or summary.', 'Thanks for reviewing — we will keep you posted.'),
    tpl('handoff-project', 'general', 'general-email', 'Project handoff', 'A structured message for delivering completed work and next steps.', 'Your project handoff from {{company.name}}', '#0f766e', 'Completed projects', 'Everything you need for handoff', 'Hi {{client.name}},\n\nYour project is ready to hand over. In this email, add links to the final files, key documentation, access details, and any agreed next steps.\n\nWe recommend saving these details somewhere your team can easily find them.', 'Please reply to confirm receipt, and let us know if you would like a walkthrough.'),
    tpl('handoff-team', 'general', 'general-email', 'Team introduction handoff', 'A warm transition that introduces a new owner or point of contact.', 'Introducing your next contact at {{company.name}}', '#2563eb', 'Account transitions', 'A smooth transition', 'Hello {{client.name}},\n\nWe are introducing the person who will support you from here. Add their name, role, contact details, and a short summary of the work already completed.\n\nThey have the background and context needed to keep everything moving smoothly.', 'Thank you for helping us make this a seamless handoff.'),
    tpl('handoff-final-delivery', 'general', 'general-email', 'Final delivery', 'A clear checklist-style note for assets, ownership, and support.', 'Final files and next steps from {{company.name}}', '#4338ca', 'Final asset delivery', 'Your final files are ready', 'Hi {{client.name}},\n\nWe are pleased to share the final deliverables. Add your download links, credentials transfer instructions, usage notes, and support window here.\n\nOwnership and next steps: add any final actions for your team.', 'Please download and review the files, then reply to confirm that everything opens correctly.'),
    tpl('general-thanks', 'general', 'general-email', 'Thank-you note', 'A simple gratitude email with a modern finish.', 'Thank you from {{company.name}}', '#16a34a', 'Client appreciation', 'Thank you', 'Hi {{client.name}},\n\nThank you for choosing {{company.name}}. We appreciate your trust and the opportunity to support your work.\n\nPlease keep this message for your records.', 'We look forward to working with you again.'),
    tpl('thanks-payment', 'general', 'general-email', 'Payment thank-you', 'A friendly confirmation that recognizes a client’s prompt payment.', 'Payment received — thank you, {{client.name}}', '#15803d', 'Paid invoices', 'Thank you for your payment', 'Hi {{client.name}},\n\nThank you for your payment for invoice {{invoice.number}}. We appreciate your prompt attention and your continued trust in {{company.name}}.\n\nYour account has been updated for our records.', 'No action is needed — we simply wanted to say thank you.'),
    tpl('thanks-referral', 'general', 'general-email', 'Referral thank-you', 'A personal note for thanking a client who recommended your business.', 'Thank you for the introduction', '#a21caf', 'Client referrals', 'Your recommendation means a lot', 'Hi {{client.name}},\n\nThank you for recommending {{company.name}}. Your trust means a great deal to us, and we are grateful that you thought of our team.\n\nWe will take excellent care of the person you introduced.', 'We truly appreciate your support and look forward to staying in touch.')
  ];
}

export function cloneStarterEmailTemplate(starter: StarterEmailTemplate, companyId: string): EmailTemplateDefinition {
  return { ...structuredClone(starter), companyId, id: undefined, createdAt: undefined, updatedAt: undefined };
}
