import { EmailColumnStyles, EmailElement, EmailSection, EmailTemplateDefinition, EmailTemplateScenario, EmailTemplateType } from '../../models/email-template-designer.model';

export type StarterEmailTemplate = Omit<EmailTemplateDefinition, 'companyId'> & { description: string; accent: string; audience: string; scenario: EmailTemplateScenario };

const defaultColumnStyles = (): EmailColumnStyles => ({ backgroundColor: '#ffffff', verticalAlign: 'top', paddingTop: 0, paddingRight: 0, paddingBottom: 0, paddingLeft: 0, borderColor: '#e2e8f0', borderWidth: 0, borderRadius: 0 });
const section = (elements: EmailElement[], backgroundColor = '#ffffff', paddingTop = 24, paddingBottom = 24): EmailSection => ({ id: crypto.randomUUID(), type: 'layout', columnWidths: [100], styles: { backgroundColor, contentWidth: 600, columnGap: 0, paddingTop, paddingRight: 28, paddingBottom, paddingLeft: 28 }, columns: [{ id: crypto.randomUUID(), styles: defaultColumnStyles(), elements }] });
const text = (content: string, fontSize = 16, fontWeight = '400', color = '#071f4d', textAlign: 'left'|'center'|'right' = 'left', backgroundColor = '#ffffff'): EmailElement => ({ id: crypto.randomUUID(), type: 'text', content, styles: { fontSize, fontWeight, fontStyle: 'normal', textAlign, color, backgroundColor, lineHeight: 1.5, paddingTop: 8, paddingRight: 8, paddingBottom: 8, paddingLeft: 8 } });
const spacer = (height: number): EmailElement => ({ id: crypto.randomUUID(), type: 'spacer', height });
const tpl = (id: string, type: EmailTemplateType, scenario: EmailTemplateScenario, name: string, description: string, subject: string, accent: string, audience: string, heading: string, body: string, cta: string): StarterEmailTemplate => ({ schemaVersion: 1, id, type, scenario, name, description, subject, accent, audience, sections: [section([text(heading, 26, '700', '#ffffff', 'left', accent), text(body), spacer(12), text(cta, 16, '700', accent)], accent, 26, 18), section([text('Thanks,\n{{company.name}}', 15, '600')], '#f8fbff', 18, 22)] });

export function createStarterEmailTemplates(): StarterEmailTemplate[] {
  return [
    tpl('invoice-polished', 'invoice', 'invoice-sending', 'Polished invoice', 'A confident invoice delivery email with clear payment details.', 'Invoice {{invoice.number}} is ready from {{company.name}}', '#2563eb', 'Professional clients', 'Invoice {{invoice.number}} is ready', 'Hi {{client.name}},\n\nYour invoice from {{company.name}} is attached for review. The current total is {{invoice.total}} and payment is due by {{invoice.dueDate}}.\n\nPlease include reference {{invoice.number}} with your payment.', 'Review the attached invoice and let us know if anything needs attention.'),
    tpl('invoice-friendly', 'invoice', 'invoice-sending', 'Friendly handoff', 'A warmer invoice email for ongoing relationships.', 'Your {{company.name}} invoice: {{invoice.number}}', '#0f766e', 'Repeat customers', 'A quick invoice note', 'Hi {{client.name}},\n\nThanks again for working with us. We have attached invoice {{invoice.number}} for {{invoice.total}}. It is due on {{invoice.dueDate}}.\n\nWe appreciate your prompt payment.', 'Have questions? Reply to this email and we will help.'),
    tpl('reminder-before-due', 'payment-reminder', 'before-due-reminder', 'Before-due reminder', 'A low-pressure reminder before the due date.', 'Upcoming payment reminder: invoice {{invoice.number}}', '#7c3aed', 'Approachable follow-ups', 'Friendly payment reminder', 'Hi {{client.name}},\n\nThis is a quick reminder that invoice {{invoice.number}} for {{invoice.total}} is due on {{invoice.dueDate}}.\n\nIf payment is already arranged, thank you and please disregard this note.', 'We are happy to help if you need anything from us.'),
    tpl('reminder-due-today', 'payment-reminder', 'due-today-reminder', 'Due today reminder', 'A clear note for payments due today.', 'Invoice {{invoice.number}} is due today', '#ea580c', 'Busy accounts teams', 'Payment due today', 'Hello {{client.name}},\n\nInvoice {{invoice.number}} for {{invoice.total}} is due today.\n\nPlease use {{invoice.number}} as the payment reference.', 'Please confirm once payment has been scheduled.'),
    tpl('reminder-overdue', 'payment-reminder', 'overdue-reminder', 'Overdue follow-up', 'A professional follow-up for invoices past due.', 'Overdue invoice {{invoice.number}} from {{company.name}}', '#dc2626', 'Overdue accounts', 'Invoice now overdue', 'Hi {{client.name}},\n\nOur records show invoice {{invoice.number}} for {{invoice.total}} was due on {{invoice.dueDate}} and still needs attention.\n\nPlease arrange payment or let us know if there is an issue.', 'Reply with an expected payment date so we can update our records.'),
    tpl('overdue-notice', 'payment-reminder', 'overdue-notice', 'Formal overdue notice', 'A firmer notice for escalated overdue accounts.', 'Notice: invoice {{invoice.number}} remains overdue', '#991b1b', 'Escalated collections', 'Overdue payment notice', 'Hello {{client.name}},\n\nInvoice {{invoice.number}} for {{invoice.total}} remains overdue after the due date of {{invoice.dueDate}}.\n\nPlease arrange payment immediately or contact us to resolve this balance.', 'We appreciate your urgent attention to this matter.'),
    tpl('letter-sending', 'letter', 'letter-sending', 'Letter delivery', 'A concise note for sending formal letters.', 'Letter from {{company.name}}', '#475569', 'Letter recipients', 'A letter is attached', 'Hi {{client.name}},\n\nPlease find the letter from {{company.name}} attached for your records.\n\nContact us if you have any questions after reviewing it.', 'Thank you for your attention.'),
    tpl('general-update', 'general', 'general-email', 'Project update', 'A clean update template for status notes.', 'Update from {{company.name}}', '#4f46e5', 'Project stakeholders', 'Here is the latest update', 'Hello {{client.name}},\n\nWe wanted to share a quick update from {{company.name}}. The key details are listed here so everything is easy to track.\n\nNext step: add your action item or summary.', 'Thanks for reviewing — we will keep you posted.'),
    tpl('general-thanks', 'general', 'general-email', 'Thank-you note', 'A simple gratitude email with a modern finish.', 'Thank you from {{company.name}}', '#16a34a', 'Client appreciation', 'Thank you', 'Hi {{client.name}},\n\nThank you for choosing {{company.name}}. We appreciate your trust and the opportunity to support your work.\n\nPlease keep this message for your records.', 'We look forward to working with you again.')
  ];
}

export function cloneStarterEmailTemplate(starter: StarterEmailTemplate, companyId: string): EmailTemplateDefinition {
  return { ...structuredClone(starter), companyId, id: undefined, createdAt: undefined, updatedAt: undefined };
}
