<!doctype html>
<html><head><meta charset="utf-8"><title>Invoice ${invoice.number?html}</title>
<style>
@page{size:A4;margin:0}*{box-sizing:border-box}body{margin:0;background:#edf2f7;color:#26364a;font:13px Arial,sans-serif}.page{width:210mm;min-height:297mm;margin:auto;background:#fff;padding:18mm 19mm;position:relative}.top{height:18mm;margin:-18mm -19mm 16mm;padding:0 19mm;background:#3478d4;color:white;display:flex;align-items:center;justify-content:space-between}.brand{font-size:18px;font-weight:700}.title{font-size:30px;font-weight:300;letter-spacing:.02em}.meta{display:grid;grid-template-columns:1fr 1fr;gap:12mm;margin-bottom:20mm}.right{text-align:right}.label{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.12em;color:#3478d4}.name{font-size:16px;font-weight:700;margin:5px 0}.lines{line-height:1.6}.facts{display:inline-grid;grid-template-columns:auto auto;gap:5px 15px;text-align:left}.facts b{text-align:right}table{width:100%;border-collapse:collapse}th{padding:9px;background:#3478d4;color:#fff;text-align:left;font-size:10px;letter-spacing:.08em}th:not(:first-child),td:not(:first-child){text-align:right}td{padding:9px;border-bottom:1px solid #c9dcf7}.totals{width:42%;margin-left:auto;margin-top:8px}.totals td{border:0;padding:5px 8px}.totals .grand{font-size:17px;font-weight:700;border-top:2px solid #3478d4;color:#245ca8}.notes{margin-top:14mm;padding:10px 12px;background:#f2f7fd;border-left:3px solid #3478d4}.footer{position:absolute;left:19mm;right:19mm;bottom:15mm;display:flex;justify-content:space-between;align-items:end;border-top:1px solid #c9dcf7;padding-top:9px}.bank{line-height:1.55}.thanks{font-weight:700;color:#245ca8;text-align:right}
</style></head><body><main class="page">
<header class="top"><div class="brand">${company.name?html}</div><div class="title">INVOICE</div></header>
<section class="meta"><div><div class="label">From</div><div class="name">${company.name?html}</div><div class="lines">${company.address?html}<br>${company.email?html}<#if company.phone?has_content><br>${company.phone?html}</#if></div></div><div class="right"><div class="facts"><span>Invoice no.</span><b>${invoice.number?html}</b><span>Issued</span><b>${invoice.date?html}</b><span>Due</span><b>${invoice.dueDate?html}</b></div></div><div><div class="label">Bill to</div><div class="name">${client.name?html}</div><div class="lines">${client.street?html}<br>${client.suburb?html}, ${client.city?html} ${client.postalCode?html}<br>${client.email?html}</div></div></section>
<table><thead><tr><th>Description</th><th>Qty / Hours</th><th>Rate</th><th>Amount</th></tr></thead><tbody><#list invoice.items as item><tr><td>${item.description?html}</td><td>${item.hours?html}</td><td>${item.rate?html}</td><td>${item.amount?html}</td></tr></#list></tbody></table>
<table class="totals"><tr><td>Subtotal</td><td>${invoice.subtotal?html}</td></tr><tr><td>VAT (${invoice.vatPercentage?html}%)</td><td>${invoice.vat?html}</td></tr><tr class="grand"><td>Total</td><td>${invoice.total?html}</td></tr></table>
<#if invoice.notes?has_content><div class="notes"><b>Notes</b><br>${invoice.notes?html}</div></#if>
<footer class="footer"><div class="bank"><div class="label">Payment reference</div>${payment.reference?html}</div><div class="thanks">Thank you for your business.</div></footer>
</main></body></html>
